name: Update Random Dev Quote

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch random dev quote
        id: fetch_quote
        run: |
          quote=$(curl -s https://quotes-github-readme.vercel.app/api?type=horizontal&theme=radical)
          echo "Quote fetched: $quote"
          echo "::set-output name=quote::$quote"

      - name: Update README with new quote
        run: |
          # Read the existing README file
          file=$(cat README.md)

          # Replace the placeholder for the dev quote with the new one
          new_file="${file//![Random Dev Quote](https:\/\/quotes-github-readme.vercel.app\/api\?type=horizontal\&theme=radical)/${{ steps.fetch_quote.outputs.quote }}"

          # Write the new content back to README.md
          echo "$new_file" > README.md

      - name: Commit and push changes
        name: Commit changes to README
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update random dev quote"
          git push
